### ISSUE TITLE
Curious - with regard to partition key ...

### ISSUE THREAD

**Issue by bdcoder2** [delange/cosmosdb-spatial-query-app#1]
Thank-you for your excellent blog: [Geospatial big data performance tests with Cosmos DB and data enrichment with Azure Synapse Analytics](https://towardsdatascience.com/geospatial-big-data-performance-tests-with-cosmos-db-and-data-enrichment-with-azure-synapse-257db7d29e41)

I noticed while reading the documentation (at: [https://github.com/delange/cosmosdb-spatial-query-perf/tree/master/AzureDataFactory](https://github.com/delange/cosmosdb-spatial-query-perf/tree/master/AzureDataFactory)) it states:

_"The partition key must be set to /properties/state"_

However, the queries used (at: [https://github.com/delange/cosmosdb-spatial-query-app](https://github.com/delange/cosmosdb-spatial-query-app)) do not seem to make use of the partition key, only the geospatial index.

We have a similar use case in which 99% of the queries are done using ST_WITHIN and ST_INTERSECTS for boundaries appearing anywhere on the globe -- and are using the document ID as the partition key; however, I am not sure if this is considered "good" practice or not -- would you be able to shed any design insights in this regard?, i.e.: does it matter what partition key you are using if the geospatial index is being used?

Thanks in advance.

**Comment by delange** [comment]
Thanks for the question.
Indexation and partitioning are different things and serve different purposes. With (geospatial)indexation you find the queried data more efficiently, while with partitioning you distribute data so that queries or data ingest can run in parallel. To perform spatial queries, it is good practice to use geospatial indexation. It is also good practice to choose a partition key that bundles your data in such a way that it minimize the inter partition/container communication. see also the guidelines at: https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#choose-partitionkey

**Comment by bdcoder2** [comment]
@delage - Thank-you for your reply and link to the partitioning guidelines.  The documentation does state "For small read-heavy containers or write-heavy containers of any size, the item ID is naturally a great choice for the partition key.".   Given our use case, it would seem to make sense to use the document ID (GUID) as the partition key (I am assuming) in order to distribute the data, as I cannot seem to find any documentation that describes a "better" way to distribute data where 99% of the queries are geospatial in nature.
